FORMAT: 1A

# Netshoes and Zattini new API

## Zattini Feature Products [/featureProducts]

### List All Products [GET]

+ Response 200 (application/json)

        {
          "message": "success",
          "isSuccess": true,
          "exception": "",
          "value": {
            "page_data": [
              {
                "recommendations": [
                  {
                    "label": "ACABOU DE CHEGAR",
                    "products": [
                      {
                        "image": {
                          "large": "//static2.netshoes.net/Produtos/tenis-jorge-bischoff-cadarco/05/E02-0299-205/E02-0299-205_detalhe1.jpg"
                        },
                        "url": "/produto/tenis-jorge-bischoff-cadarco-E02-0299-205",
                        "price": {
                          "original_price": "",
                          "saving": "",
                          "payment_condition": "10x de R$ 39,99",
                          "actual_price": "R$ 399,90"
                        },
                        "name": "Tênis Jorge Bischoff Cadarço",
                        "stamps": [
                          {
                            "id": "6",
                            "label": "Novidade"
                          }
                        ]
                      },
                      {
                        "image": {
                          "large": "//static2.netshoes.net/Produtos/tenis-jorge-bischoff-cadarco/05/E02-0299-205/E02-0299-205_detalhe1.jpg"
                        },
                        "url": "/produto/tenis-jorge-bischoff-cadarco-E02-0299-205",
                        "price": {
                          "original_price": "",
                          "saving": "",
                          "payment_condition": "10x de R$ 39,99",
                          "actual_price": "R$ 399,90"
                        },
                        "name": "Tênis Jorge Bischoff Cadarço",
                        "stamps": [
                          {
                            "id": "6",
                            "label": "Novidade"
                          }
                        ],
                        "badge": {
                          "strength": "",
                          "value": "-25%"
                        }
                      }
                    ]
                  },
                  {
                    "label": "PARA ANDAR NA MODA",
                    "products": [
                      {
                        "image": {
                          "large": "//static5.netshoes.net/Produtos/sandalia-walkabout-meia-pata/09/H25-0074-209/H25-0074-209_detalhe1.jpg"
                        },
                        "url": "/produto/sandalia-walkabout-meia-pata-H25-0074-209",
                        "price": {
                          "original_price": "",
                          "saving": "",
                          "payment_condition": "5x de R$ 25,98",
                          "actual_price": "R$ 129,90"
                        },
                        "name": "Sandália Walkabout Meia Pata",
                        "stamps": [
                          {
                            "label": "2 por R$159,90"
                          }
                        ],
                        "badge": {
                          "strength": "",
                          "value": "-25%"
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
